services:
  - type: web
    name: rizal-backend
    env: docker
    dockerfilePath: ./Backend/Dockerfile
    dockerContext: ./Backend
    region: singapore
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rizal-db
          property: connectionString

databases:
  - name: rizal-db
    databaseName: fastapi_db
    user: postgres
    region: singapore
    plan: free
